version: '2'
services:
  neo4j:
    image: neo4j:latest
    # environment:
    #   NEO4J_AUTH: 'neo4j/myPassword123'
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - 'neo4j_data:/bitnami'
volumes:
  neo4j_data:
    driver: local
